# docker-compose.yml
version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:6
    container_name: parliament-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=parliament-watch
    volumes:
      - mongodb-data:/data/db
    networks:
      - parliament-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: parliament-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://${MONGO_ROOT_USER:-admin}:${MONGO_ROOT_PASSWORD:-password}@mongodb:27017/parliament-watch?authSource=admin
    depends_on:
      - mongodb
    networks:
      - parliament-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: parliament-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - parliament-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/health.html"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  parliament-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local