# fly.toml - Combined application configuration

app = "parliament-watch"
primary_region = "yyz"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[build]
  [build.args]
    NODE_VERSION = "18"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/api/health"
    protocol = "http"

[mounts]
  source = "parliament_data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 27017
  processes = ["mongo"]

  [[services.ports]]
    port = 27017
    handlers = ["pg_tls"]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[processes]
  app = "node src/server.js"
  mongo = "mongod --dbpath /data/db --auth"

[env.mongo]
  MONGO_INITDB_ROOT_USERNAME = "pw_admin"
  MONGO_INITDB_ROOT_PASSWORD = "REPLACE_WITH_SECURE_PASSWORD"
  MONGO_INITDB_DATABASE = "parliament-watch"

[env.app]
  MONGODB_URI = "mongodb://pw_admin:REPLACE_WITH_SECURE_PASSWORD@localhost:27017/parliament-watch?authSource=admin"