app = "parliament-watch"
primary_region = "yyz"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 80  # Changed to 80 since frontend uses Nginx
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/health.html"  # Changed to match the frontend health check
    protocol = "http"