app = "parliament-watch"
primary_region = "yyz"

[build]
  dockerfile = "Dockerfile"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512  # Much less memory needed for serving static files

[http_service]
  internal_port = 80  # Nginx uses port 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/health.html"
    protocol = "http"