# fly.toml - Combined application configuration

app = "parliament-watch"
primary_region = "yyz"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[build]
  [build.args]
    NODE_VERSION = "18"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/api/health"
    protocol = "http"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[processes]
  app = "node src/server.js"

